// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgAvPCV4Qjdmmzu9T6rQY85XYoibHjrUw',
    appId: '1:749110778768:web:02d041f48cb936f120f115',
    messagingSenderId: '749110778768',
    projectId: 'office-management-app-ac9d8',
    authDomain: 'office-management-app-ac9d8.firebaseapp.com',
    storageBucket: 'office-management-app-ac9d8.firebasestorage.app',
    measurementId: 'G-T1S6RVX3FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuFbyswk0_ET_UPp4tRXOdzwv9l8nIYk',
    appId: '1:749110778768:android:a97c33ff1ca3702820f115',
    messagingSenderId: '749110778768',
    projectId: 'office-management-app-ac9d8',
    storageBucket: 'office-management-app-ac9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKFlg4FREGn94vjCCOxHWUVVin48W3EA',
    appId: '1:749110778768:ios:f0df61cf3a3ad8e320f115',
    messagingSenderId: '749110778768',
    projectId: 'office-management-app-ac9d8',
    storageBucket: 'office-management-app-ac9d8.firebasestorage.app',
    iosBundleId: 'com.example.officeTaskManagemet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIKFlg4FREGn94vjCCOxHWUVVin48W3EA',
    appId: '1:749110778768:ios:f0df61cf3a3ad8e320f115',
    messagingSenderId: '749110778768',
    projectId: 'office-management-app-ac9d8',
    storageBucket: 'office-management-app-ac9d8.firebasestorage.app',
    iosBundleId: 'com.example.officeTaskManagemet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgAvPCV4Qjdmmzu9T6rQY85XYoibHjrUw',
    appId: '1:749110778768:web:8312caa39039e86920f115',
    messagingSenderId: '749110778768',
    projectId: 'office-management-app-ac9d8',
    authDomain: 'office-management-app-ac9d8.firebaseapp.com',
    storageBucket: 'office-management-app-ac9d8.firebasestorage.app',
    measurementId: 'G-7F587HGRXT',
  );
}
